# -*- coding: utf-8 -*-
"""Copy_of_Intro_to_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/yousufsayad2/yosef-Ai/blob/main/Copy_of_Intro_to_python.ipynb
"""


import os
from google import genai

def main():
    api_key = input("Enter your Gemini API Key: ").strip()

    client = genai.Client(api_key=api_key)

    chat = client.chats.create(
        model="gemini-3.5-flash"
    )

    print("=" * 45)
    print("🤖 Yosef AI is online!")
    print("Type 'exit' to quit.")
    print("=" * 45)

    while True:
        user = input("\nYou: ")

        if user.lower() == "exit":
            print("Goodbye!")
            break

        try:
            response = chat.send_message(user)
            print("\nYosef AI:", response.text)
        except Exception as e:
            print("Error:", e)

main()